### ISSUE TITLE
Courses API

### ISSUE THREAD

**Issue by ricelbai** [rice-apps/scheduleplanner#4]
You might consider gathering course data using the courses API described at https://docs.rice.edu/confluence/display/~lpb1/Courses+API .

**Comment by mschurr** [comment]
Is there an advantage to using this over the current feed we are using?

See:
https://github.com/rice-apps/scheduleplanner/blob/master/backend/helpers/CourseDataParser.php

**Comment by mschurr** [comment]
We are now using this API instead.
